### ISSUE TITLE
Login doesn't fire native FB app on iOS

### ISSUE THREAD

**Issue by sserdyuk** [Telerik-Verified-Plugins/Facebook#23]
I was using an old version of this plugin in the app and had no problems, but was forced to upgrade after receiving a notice on API 2.0 deprecation. The new version works fine in every regard except that it doesn't open the native FB app on iOS. Instead, it opens a Safari page and offers me to log into FB via web. What can I do to help troubleshooting this?

**Comment by kaansoral** [comment]
Absolutely nothing, it's strategic (and set in ~stone on the sdk)

Less people login to your app, more win for fb :)

**Comment by sserdyuk** [comment]
I am not buying it. What's the benefit for FB? 

I have found the following bit on the Wizcorp plugins FAQ: 

Problem: Calling the login function always opens the web dialog even though the native app is installed on the device.
Solution: Switch "deep linking" to ON in the Facebook developer website settings for your application

Is this true? The only way I can enable Deep linking in FB app settings is to turn on the "Single Sign On" option. What would be the consequences of that?

**Comment by rossi256** [comment]
I have the same problem - as described also in #18 
In testflight app, i always have the "already authorized" safari page coming up - i am still hoping that maybe the production app will not show that, since in your app in FB you are supposed to enter the correct apple app store id and that might mean its only really working in production (?)

i do not think the deep linking will do much change...i have tried a lot with that stuff...

**Comment by kaansoral** [comment]
I don't think anyone should buy it, so I support you on your decision

I wish I didn't integrate fb on my project, lost so much time and effort, didn't integrate fb on my new project

You can read more about it here: https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9

**Comment by sserdyuk** [comment]
So, based on the post, it is working as designed by FB on iOS9+.
